import { chromium } from 'playwright-core'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] })
const p = await b.newPage()
p.on('console', m => console.log('console.' + m.type(), m.text().slice(0, 400)))
p.on('pageerror', e => console.log('pageerror', String(e).slice(0, 600)))
p.on('requestfailed', r => console.log('reqfail', r.url(), r.failure()?.errorText))
await p.goto(process.argv[2] ?? 'http://localhost:4173/', { waitUntil: 'networkidle' })
await p.waitForTimeout(4000)
console.log('root html:', (await p.evaluate(() => document.getElementById('root').innerHTML)).slice(0, 200))
await b.close()
